@startuml Campamento

top to bottom direction

entity "users" as usuarios {
    + user_id : int
    + user_id2 : string
    + email : string
    + password : string
    + role : int <<0 = tutor, 1 = monitor, 2 = admin>>
    + enabled : bool
}

entity "user_details" as detalles_usuarios {
    + detail_id : int
    + user_id : int
    + user_name : string
    + user_email : string
    + user_relationship : string
    + user_birth_date : date
    + user_dni : string
    + user_phone_number : string
}

entity "participants" as participantes {
    + participant_id : int
    + participant_id2 : string
    + user_id : int
    + full_name : string
    + birth_date : date
    + address : string
    + allergies : string
    + special_needs : string
    + medical_treatment : string
}

entity "schedule" as cronograma {
    + schedule_id : int
    + schedule_id2 : string
    + participant_id : int
    + start_day : date
    + end_day : date
}

entity "activities" as actividades {
    + activity_id : int
    + activity_id2 : string
    + name : string
    + description : string
    + date : date
    + time : time
    + max_participants : int
}

entity "activities_monitors" as actividades_monitores {
    + relation_id : int
    + activity_id : int
    + monitor_id : int
}

entity "activities_participants" as actividades_participantes {
    + relation_id : int
    + activity_id : int
    + participant_id : int
}

entity "attendance" as asistencias {
    + attendance_id : int
    + attendance_id2 : string
    + activity_id : int
    + participant_id : int
    + check_in : datetime
    + check_out : datetime
}

entity "payments" as pagos {
    + payment_id : int
    + payment_id2 : string
    + user_id : int
    + amount : decimal
    + date : date
    + status : string
    + method : string
}

entity "blog_posts" as publicaciones_blog {
    + post_id : int
    + post_id2 : string
    + admin_id : int
    + title : string
    + content : text
    + date_published : date
}

usuarios ||--o{ detalles_usuarios : "1,1 - 1,1"
usuarios ||--o{ participantes : "1,N - 1,1"
usuarios ||--o{ pagos : "1,N - 1,1"
usuarios ||--o{ actividades_monitores : "1,N - 1,1"
usuarios ||--o{ publicaciones_blog : "1,N - 1,1"

participantes ||--o{ cronograma : "1,1 - 1,N"
participantes ||--o{ actividades_participantes : "1,1 - N,1"
participantes ||--o{ asistencias : "1,1 - N,1"

actividades ||--o{ actividades_monitores : "1,1 - N,1"
actividades ||--o{ actividades_participantes : "1,1 - N,1"
actividades ||--o{ asistencias : "1,1 - N,1"

@enduml